nguage: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install

script:
    - vendor/bin/phpunit test/StreamTest.php
    - echo "Running tests requiring tty"; phpunit --group tty
