nguage: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
    - composer --version
    - COMPOSER_ROOT_VERSION=dev-master composer install

script:
    - vendor/bin/phpunit test/StreamTest.php
